### ISSUE TITLE
removing reliance on Third-Party APIs [abandoned]

### ISSUE THREAD

**Issue by su77ungr** [RayVentura/ShortGPT#15]
Edit: 
@elevenlabs is this a joke? @maxilevi sell-out
```bash

ERROR| Exception : Error in response, 401 , message: {"detail":{"status":"quota_exceeded","message":"Unusual activity detected. Free Tier usage disabled. If you are using proxy/VPN you might need to purchase a Paid Plan to not trigger our abuse detectors. Free Tier only works if users do not abuse it, for example by creating multiple free accounts. If we notice that many people try to abuse it, we will need to reconsider Free Tier altogether. Please play fair.\nPlease purchase any Paid Subscription to continue."}}

```

**Comment by dolev765** [comment]
If you do I am going to contrubute my whole eleven labs budget to ya . around 100-200 dollars

**Comment by dolev765** [comment]
so keep me updated @su77ungr

**Comment by dolev765** [comment]
Quick suggestion you can try and use tiktok id

**Comment by RayVentura** [comment]
No followup. Closed.

**Comment by dolev765** [comment]
Na this still open

**Comment by su77ungr** [comment]
Regarding the GitHub issue, I didn't have anything to comment on - i have to take vacation at some point in time lol.

EVERYTHING is handled offline exceot the youtube API  

My code now includes YouTube integration ` search_res = youtube.search().list(**search_params).execute()`, which serves as an additional source for gathering footage. This is particularly useful when dealing with niche / comedy / meme topics where stock footage is not available.

My llama2 agent surpasses gpt-3.5 in terms of raw quality without relying on prompted templates. Someone banned me from the dc for no reason, so I see no need to make it public. Just a follow up post. 

![image](https://github.com/RayVentura/ShortGPT/assets/69374354/2f4b93fc-cb96-46db-9602-e2f1c7e3da28)

The demo is quite impressive, you can find it here: https://vimeo.com/851101834?share=copy. 

It does not include recursive checks and timestamp analysis for QC checks tho (with that and frame extraction you might get way better results; image / setting recognition every n-th frame is not that computational intense) 

@dolev765 were you referencing to the tiktok generic voice? that can be cloned in bark

**Comment by wakaztahir** [comment]
@su77ungr Hi the video you created, is it using FreeShortGPT, How can I do the same where's the code , I'd really appreciate if you could share

**Comment by dolev765** [comment]
> Regarding the GitHub issue, I didn't have anything to comment on - i have to take vacation at some point in time lol.
> 
> EVERYTHING is handled offline exceot the youtube API  
> 
> My code now includes YouTube integration ` search_res = youtube.search().list(**search_params).execute()`, which serves as an additional source for gathering footage. This is particularly useful when dealing with niche / comedy / meme topics where stock footage is not available.
> 
> My llama2 agent surpasses gpt-3.5 in terms of raw quality without relying on prompted templates. Someone banned me from the dc for no reason, so I see no need to make it public. Just a follow up post. 
> 
> ![image](https://github.com/RayVentura/ShortGPT/assets/69374354/2f4b93fc-cb96-46db-9602-e2f1c7e3da28)
> 
> The demo is quite impressive, you can find it here: https://vimeo.com/851101834?share=copy. 
> 
> It does not include recursive checks and timestamp analysis for QC checks tho (with that and frame extraction you might get way better results; image / setting recognition every n-th frame is not that computational intense) 
> 
> @dolev765 were you referencing to the tiktok generic voice? that can be cloned in bark
>                 
>        

Exactly but you found a better way at it with bark I see

**Comment by su77ungr** [comment]
@wakaztahir added a demo of the youtube implementation here. Use it with landscape mode only on the creation with stock footage tab. Aspect ratio and content quality triage might need attention too https://github.com/RayVentura/ShortGPT/compare/stable...su77ungr:FreeShortGPT:stable
