### ISSUE TITLE
i see this Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by simons1010** [RayVentura/ShortGPT#18]
after installing it on windows
and when I want to enter my API in the config and click save

I see this error: Expecting value: line 1 column 1 (char 0)
I tried 3 browsers but the same error 

even on the first tab for every option that I choose, I see the same error

**Comment by RayVentura** [comment]
Try to close the Web UI and delete  the .database/api_db.json file?

Btw, what version of python are you running?

**Comment by SinoMiles** [comment]
same issues ,python version is 3.

> Try to close the Web UI and delete the .database/api_db.json file?
> 
> Btw, what version of python are you running?

**Comment by thebe4st** [comment]
same issue,python version is 3.10,what  version of python should i use.

**Comment by RayVentura** [comment]
I'm running on 3.9, but I don't know what exactly caused that. Are you guys running it locally/ on google colab? Plus, is there a more detailed stacktrace of the error ?

**Comment by om19** [comment]
same issue

**Comment by Yucheng301** [comment]
Same issue

**Comment by yishiliuc** [comment]
> I'm running on 3.9, but I don't know what exactly caused that. Are you guys running it locally/ on google colab? Plus, is there a more detailed stacktrace of the error ?

same issue, py3.10.9, running it locally, no error in cmd, but any browser is the error, strange

**Comment by jendy2012** [comment]
Guys, it seems I've found the issue. Please test in an appropriate network environment or VPN setting.
