### ISSUE TITLE
not found shortgpt.py file

### ISSUE THREAD

**Issue by readyjamil** [RayVentura/ShortGPT#19]
as per the below we have to locate "shortgpt.py" but code not have this file. 
Step 4: Install Python Dependencies
Open a terminal or command prompt.

Navigate to the directory where shortgpt.py is located (the cloned repo).

Execute the following command to install the required Python dependencies:

**Comment by FeirNox** [comment]
It does say locate "shortgpt.py", but its actually called "runShortGPT.py" try that instead.

**Comment by RayVentura** [comment]
You guys are right, there is a typo in the README, I just fixed it, thanks
