### ISSUE TITLE
 raise IOError(("MoviePy error: failed to read the duration of file %s.\n"

### ISSUE THREAD

**Issue by KalvinThien** [RayVentura/ShortGPT#23]
Today, I use Video Automation with stock assets and get back this error , I use 🎞️ google colab .  thank you 

Error   File "/content/ShortGPT/gui/video_automation_ui.py", line 95, in respond
    video_path = makeVideo(script, language.value, isVertical, progress=progress)
  File "/content/ShortGPT/gui/video_automation_ui.py", line 46, in makeVideo
    for step_num, step_info in shortEngine.makeShort():
  File "/content/ShortGPT/shortGPT/engine/abstract_content_engine.py", line 72, in makeShort
    self.stepDict[currentStep]()
  File "/content/ShortGPT/shortGPT/engine/content_video_engine.py", line 139, in _editAndRenderShort
    videoEditor.renderVideo(outputPath, logger=self.logger)
  File "/content/ShortGPT/shortGPT/editing_framework/editing_engine.py", line 92, in renderVideo
    engine.generate_video(self.schema, outputPath, logger=logger)
  File "/content/ShortGPT/shortGPT/editing_framework/core_editing_engine.py", line 53, in generate_video
    clip = self.process_video_asset(asset)
  File "/content/ShortGPT/shortGPT/editing_framework/core_editing_engine.py", line 179, in process_video_asset
    clip = VideoFileClip(**params)
  File "/usr/local/lib/python3.10/dist-packages/moviepy/video/io/VideoFileClip.py", line 88, in __init__
    self.reader = FFMPEG_VideoReader(filename, pix_fmt=pix_fmt,
  File "/usr/local/lib/python3.10/dist-packages/moviepy/video/io/ffmpeg_reader.py", line 35, in __init__
    infos = ffmpeg_parse_infos(filename, print_infos, check_duration,
  File "/usr/local/lib/python3.10/dist-packages/moviepy/video/io/ffmpeg_reader.py", line 289, in ffmpeg_parse_infos
    raise IOError(("MoviePy error: failed to read the duration of file %s.\n"

**Comment by RayVentura** [comment]
Hmm.. I think that the link for the asset of that it pulls from Pexels might be unavailable, I will try to reproduce.

**Comment by slaser79** [comment]
I had the same issue and it was related to https url to vimeo. I temporarily fixed this with the following code that downloaded the video file to a temporary file on line 179 of core_editing_engine.py:
`  
def process_video_asset(self, asset: Dict[str, Any]) -> VideoFileClip:
        
        params = {
            'filename': asset['parameters']['url']
        }
        if 'audio' in asset['parameters']:
            params['audio'] = asset['parameters']['audio']
        #Check url is https then download file to temp file first
        if params['filename'].startswith('https'):
            import requests
            import tempfile
            temp_file = tempfile.NamedTemporaryFile(delete=False)
            temp_file.write(requests.get(params['filename']).content)
            params['filename'] = temp_file.name
            clip = VideoFileClip(**params)
            temp_file.close()
        else:
            clip = VideoFileClip(**params)
        return self.process_common_visual_actions(clip, asset['actions'])

`

**Comment by lsanchezvv** [comment]
@slaser79 had the same issue and this worked. It's tricky because it seems that when some videos are not found, it causes the error. Had to change my prompts and videos to make it work. Also had to choose vertical option as landscape errored out in one of the prompts

**Comment by RayVentura** [comment]
> I had the same issue and it was related to https url to vimeo. I temporarily fixed this with the following code that downloaded the video file to a temporary file on line 179 of core_editing_engine.py: ` def process_video_asset(self, asset: Dict[str, Any]) -> VideoFileClip:
> 
> ```
>     params = {
>         'filename': asset['parameters']['url']
>     }
>     if 'audio' in asset['parameters']:
>         params['audio'] = asset['parameters']['audio']
>     #Check url is https then download file to temp file first
>     if params['filename'].startswith('https'):
>         import requests
>         import tempfile
>         temp_file = tempfile.NamedTemporaryFile(delete=False)
>         temp_file.write(requests.get(params['filename']).content)
>         params['filename'] = temp_file.name
>         clip = VideoFileClip(**params)
>         temp_file.close()
>     else:
>         clip = VideoFileClip(**params)
>     return self.process_common_visual_actions(clip, asset['actions'])
> ```
> 
> `

Did that fix all bugs related to MoviePy vimeo urls causing that crash?

**Comment by fxgeoffrey** [comment]
same issue.

**Comment by RayVentura** [comment]
This commit should've fixed the problems with the urls on google colab for everyone.
https://github.com/RayVentura/ShortGPT/commit/a8eb19e5cb97b903ebea3ca4c8fe06833c41b442
