### ISSUE TITLE
Support to use own images for the creation of custom shorts

### ISSUE THREAD

**Issue by vembarrajan** [RayVentura/ShortGPT#27]
Good day, Thanks for the framework. It would be great to add the ability to use own images for shorts & videos.  Currently it's supporting only audio & video. 

<img width="1346" alt="image" src="https://github.com/RayVentura/ShortGPT/assets/13500667/5c3f861d-9ced-437c-813a-a5a689e09896">

**Comment by RayVentura** [comment]
> Good day, Thanks for the framework. It would be great to add the ability to use own images for shorts & videos. Currently it's supporting only audio & video.
> <img alt="image" width="1346" src="https://user-images.githubusercontent.com/13500667/254826090-5c3f861d-9ced-437c-813a-a5a689e09896.png">

For automated purposes, you can drag and drop a file in the public folder and use it from the asset_db in the code, it will auto detect it if you call load_local_assets
