### ISSUE TITLE
Discord spam

### ISSUE THREAD

**Issue by cozmycc** [RayVentura/ShortGPT#3]
Can you please not spam random Discord servers? It is against the Discord ToS and has been reported.

**Comment by CurioCrafter** [comment]
Hi, I only posted it once on AI discord servers and read the rules where it was posted, which server and where in the TOS are you referring to?

**Comment by cozmycc** [comment]
It is not my responsibility to inform you of the Discord ToS, that is yours. If anyone gets spam concerning this, report it in-app under Spam.

https://discord.com/safety/360044103651-reporting-abusive-behavior-to-discord

**Comment by RayVentura** [comment]
Hi @Dooder07,

Thank you for bringing this up. I kindly request that you refrain from posting issues on this GitHub repository that are unrelated to the specific code malfunctioning. This allows us to maintain a clear focus on addressing technical problems.

If you encounter any difficulties or have concerns, please feel free to reach out to me directly via Discord or Twitter, and I'll be more than happy to assist you.

Thank you for your understanding and cooperation.

Best regards,
Ray.

**Comment by cozmycc** [comment]
> Hi @Dooder07,
> 
> Thank you for bringing this up. I kindly request that you refrain from posting issues on this GitHub repository that are unrelated to the specific code malfunctioning. This allows us to maintain a clear focus on addressing technical problems.
> 
> If you encounter any difficulties or have concerns, please feel free to reach out to me directly via Discord or Twitter, and I'll be more than happy to assist you.
> 
> Thank you for your understanding and cooperation.
> 
> Best regards, Ray.

You're welcome. As a developer, trust me, I fully understand this isn't the appropriate location for such a discussion. But at any rate it could affect your standing with Discord if you continue to send unsolicited marketing/advertising, consider yourself warned.
