### ISSUE TITLE
Expecting ',' delimiter: line 1 column 257 (char 256)

### ISSUE THREAD

**Issue by cced3000** [RayVentura/ShortGPT#30]
Automate a video with stock assets：

Step 1 _generateTempAudio
Step 2 _speedUpAudio
Step 3 _timeCaptions
Detected language: English
100% 5117/5117 [00:01<00:00, 2592.00frames/s]
Step 4 _generateVideoSearchTerms
Expecting ',' delimiter: line 1 column 257 (char 256)
not the right format

**Comment by RayVentura** [comment]
Do you have a more detailed stacktrace?

**Comment by Vermath** [comment]
Also receiving the same error but it does proceed past this step and begin rendering a video.
