### ISSUE TITLE
Add Chinese support

### ISSUE THREAD

**Issue by tianheil3** [RayVentura/ShortGPT#35]
I hope to increase support for Chinese ，Really

**Comment by KalvinThien** [comment]
https://github.com/RayVentura/ShortGPT/issues/24
Chinese do not support right now !!

**Comment by iorilu** [comment]
> I hope to increase support for Chinese ，Really

you can make a english video , then translate to Chinese

**Comment by jmc-123** [comment]
Does Japanese support?

**Comment by KalvinThien** [comment]
currently supports 80 languages in the world.
 Includes Japanese, Chinese with Edge-tts
