### ISSUE TITLE
Video without any sound

### ISSUE THREAD

**Issue by egkodin** [RayVentura/ShortGPT#38]
After rendering, I view the finished video and watch it with sound in the web interface, but when I download it, it is completely without sound. What could be the problem?

**Comment by RayVentura** [comment]
It's a codec issue, I'm currently working on a fix. Should be fixed within the next 24 hours.

**Comment by mahevstark** [comment]
@egkodin meanwhile audio will actually play on another android/windows device or uploaded to youtube.

**Comment by RayVentura** [comment]
Is the problem still persisting?

**Comment by egkodin** [comment]
> Is the problem still persisting?

Now it works! Thank you!
