### ISSUE TITLE
Hi RayVentura

### ISSUE THREAD

**Issue by KalvinThien** [RayVentura/ShortGPT#4]
Can you add Vietnamese language on Google Colab?
thank you very much

**Comment by RayVentura** [comment]
Hey @KalvinThien the current voice capabilities of ShortGPT are tied to ElevenLabs, to implement Vietnamese, we would either have to wait for them to implement it, or switch voice engines.

**Comment by KalvinThien** [comment]
I know of some other tools that have language capabilities of more than 100 countries, that provide APIs to use. 
If I want to switch to that API, where do I need to fix it in your code?

**Comment by RayVentura** [comment]
What's the other tool? I can add support for it. If you want to do it yourself, you go under shortGPT/audio/, and look how eleven_voice_module is implemented. You just copy it and redefine the functions using your own API. As long as it inherits the VoiceModule class, it'll work in contentEngines.

**Comment by KalvinThien** [comment]
many tools BRO
+ https://ttsfree.com/
+ https://viettelgroup.ai/service/tts
+ https://fpt.ai/tts
+ Vbee.vn
+ In addition, if you can use Microsoft's Edge_tts module, you can completely read very good content for free

**Comment by RayVentura** [comment]
Thanks for the list I'll implement a free tts module soon.
