### ISSUE TITLE
✨ [Feature Request / Suggestion]: GPT3 error: Rate limit

### ISSUE THREAD

**Issue by donghao95** [RayVentura/ShortGPT#48]
### Suggestion / Feature Request

ERROR | Exception : GPT3 error: Rate limit reached for default-gpt-3.5-turbo in organization on requests per min. Limit: 3 / min. Please try again in 20s. Contact us through our help center at help.openai.com if you continue to have issues. Please add a payment method to your account to increase your rate limit. Visit https://platform.openai.com/account/billing to add a payment method.

The free chatGPT API has rate limits. How can I adjust and decrease the speed in the code?

**Comment by dreammis** [comment]
you need paid gpt api. otherwise this program won't run properly.

**Comment by RayVentura** [comment]
Yes. Please upgrade to the paid API so it can run smoothly. Shorts cost less than 0.01$ to produce each, for the moment, so it's not a very expensive cost.

**Comment by donghao95** [comment]
> Yes. Please upgrade to the paid API so it can run smoothly. Shorts cost less than 0.01$ to produce each, for the moment, so it's not a very expensive cost.

Thank you for your reply. Unfortunately, I am unable to use Shorts as I am unable to activate a credit card in China.

**Comment by RayVentura** [comment]
> in China.

Oh, really? Alright, give me a bit of time, and I'll put a rate limit.
I've put it in the project's tracker, you can see the overall progress from there.
https://github.com/users/RayVentura/projects/1/views/1?pane=issue&itemId=34325211

**Comment by donghao95** [comment]
> > in China.
> 
> Oh, really? Alright, give me a bit of time, and I'll put a rate limit. I've put it in the project's tracker, you can see the overall progress from there. https://github.com/users/RayVentura/projects/1/views/1?pane=issue&itemId=34325211

That's okay, I also realize that adding a rate limit would affect the efficiency of the project. I will try to find a new paid account on my own later. Please don't spend any more time on this issue.

**Comment by RayVentura** [comment]
Thanks!

**Comment by KalvinThien** [comment]
About the account, you should buy 1 available nick $ 120, use it for about 30 days - 60 days (in Vietnam it usually costs from $ 1 - $ 10 without warranty)
Unlimited requests, combined with turbo-3.5-16k model will minimize the cost of using Open AI key to the maximum.

**Comment by donghao95** [comment]
> About the account, you should buy 1 available nick $ 120, use it for about 30 days - 60 days (in Vietnam it usually costs from $ 1 - $ 10 without warranty) Unlimited requests, combined with turbo-3.5-16k model will minimize the cost of using Open AI key to the maximum.

OpenAI has restrictions on credit cards from China, so I am unable to use my own credit card. I will either need to borrow a friend's card or purchase a pre-paid account. Thank you for your assistance, I will try to resolve this issue on my own.

**Comment by KalvinThien** [comment]
@donghao95 you are wrong, they only support cards from some countries, not only China.
if you want to buy some account just for content using API then i can totally share the link for you to buy!!

**Comment by geezah** [comment]
I have paid GPT, but I still got the following error after my first run:
`Traceback Info : File "shortgpt/gui/short_automation_ui.py", line 71, in create_short for step_num, step_info in shortEngine.makeContent(): File "shortgpt/shortGPT/engine/abstract_content_engine.py", line 71, in makeContent self.stepDict[currentStep]() File "shortgpt/shortGPT/engine/facts_short_engine.py", line 20, in _generateScript self._db_script = facts_gpt.generateFacts(self._db_facts_type) File "shortgpt/shortGPT/gpt/facts_gpt.py", line 6, in generateFacts result = gpt_utils.gpt3Turbo_completion(chat_prompt=chat, system=system, temp=1.3) File "shortgpt/shortGPT/gpt/gpt_utils.py", line 88, in gpt3Turbo_completion raise Exception("GPT3 error: %s" % oops)`

These were my configurations for generating content:
![image](https://github.com/RayVentura/ShortGPT/assets/50274951/d99cd169-805a-44d6-9d96-e5a50d38c1b0)

I have also entered my API keys into all the fields in the `Config` tab.

**Comment by alexdo83** [comment]
@KalvinThien giá con 120$ bao xiền đấy bạn?

**Comment by KalvinThien** [comment]
có chỗ bán 10k . có chỗ 150k , có chỗ 85k 
hiện tại thì không chỗ nào bảo hành hết , tài khoản hên xui . 
khoảng 1 tháng rưỡi trước thì 1 tk 20k bảo hành 2 tháng

**Comment by alexdo83** [comment]
Bạn mua bên nào vậy? Cho mình xin link? Gửi fb giúp mình với https://www.facebook.com/anhdo2808

**Comment by cocobeach** [comment]
Hi what are the implications of changing models, I would like to generate longer vids and use gpt 3.5 16k or GPT4 that has 8k context, is there a way of managing the models?
