### ISSUE TITLE
No audio in video

### ISSUE THREAD

**Issue by mahevstark** [RayVentura/ShortGPT#5]
I've eleven labs key set, and characters are also being consumed on each try, I've tried 3 times with different configuration, there is no audio (I'm sure) in the generated video. and in directory audio files exist too, and they play just fine. Please let me know what do you need more. 

Versions:
MacOS
ffmpeg version 6.0 Copyright (c) 2000-2023 the FFmpeg developers
(env) (base) mahev@Mahevs-MacBook-Pro shortgpt % convert --version
Version: ImageMagick 7.1.1-12 Q16-HDRI aarch64 21239 https://imagemagick.org
Copyright: (C) 1999 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI Modules OpenMP(5.0) 
Delegates (built-in): bzlib fontconfig freetype gslib heic jng jp2 jpeg jxl lcms lqr ltdl lzma openexr png ps raw tiff webp xml zlib
Compiler: gcc (4.2)

**Comment by RayVentura** [comment]
Hey @mahevstark. Can you share your video here so I can look at it?

**Comment by mahevstark** [comment]
Hi @RayVentura I'm so sorry this was a mistake, actually video doesn't have audio in safari or mac's video player, but it has audio when played in visual studio code, or on youtube or on a phone. But anyways you might want to improve it, I'm attaching a detailed video I recorded for you so you might understand what's wrong. I'll close this issue now, Thank you, great work ❤️

Issue Video: https://youtu.be/FvERLkSTR0M (Video will be available after 80 minutes of this comment's time, still processing the HD version)

**Comment by RayVentura** [comment]
Thanks for the video. You're right, there is a codec issue making mac users not be able to hear it when opening the video with the main players, and it shouldn't happen. As you noticed, the video is fine when uploaded on YouTube, or ran on vscode. I'll definitely try to solve that.
