### ISSUE TITLE
❓ [Question]: 

### ISSUE THREAD

**Issue by MrSipping** [RayVentura/ShortGPT#82]
### Your Question

do you need paid openAi? because when I try to Automate the creation of shorts I get this message "ERROR | Exception : GPT3 error: You exceeded your current quota, please check your plan and billing details." Instead when I try to make Automate a video with stock assets it continues to run but nothing comes out

**Comment by RayVentura** [comment]
Yes, you do need a paid OpenAI api to avoid the rate limit.
