### ISSUE TITLE
❓ [Question]: installation error

### ISSUE THREAD

**Issue by DingSenSong** [RayVentura/ShortGPT#85]
### Your Question

      <string>:45: RuntimeWarning: Pillow 9.0.0 does not support Python 3.11 and does not provide prebuilt Windows binaries. We do not recommend building from source on Windows.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pillow
Failed to build pillow
ERROR: Could not build wheels for pillow, which is required to install pyproject.toml-based projects

**Comment by DingSenSong** [comment]
This error occurred during my installation. Could you help me solve it? I have installed pyproject.toml-based projects

**Comment by DingSenSong** [comment]
已经解决了，是Python版本的问题，3.11是不可以，3.9是可以的

**Comment by RayVentura** [comment]
You need to install either python 3.10, or 3.9
