### ISSUE TITLE
OPEN AI❓ [Question]: 

### ISSUE THREAD

**Issue by axen1** [RayVentura/ShortGPT#87]
### Your Question

![image](https://github.com/RayVentura/ShortGPT/assets/31828262/48f00bf3-6e01-416b-8e15-7cc8bad92728)
I enter the config.py api key in the config file, the error appears on the screen.

**Comment by RayVentura** [comment]
You should enter it in the config tab on the web UI, not in a file

**Comment by axen1** [comment]
So how can I do it? can you post a screenshot?

**Comment by rpp-Little-pig** [comment]
![image](https://github.com/RayVentura/ShortGPT/assets/103187300/1e9ae49d-2f20-416d-bf9e-b2dbbc3c8f86)
