### ISSUE TITLE
❓ [Question]: how can i use a custom endpoint for the openai api ? 

### ISSUE THREAD

**Issue by anythingbutme** [RayVentura/ShortGPT#90]
### Your Question

...

**Comment by yaohongfenglove** [comment]
Add the following line inside the function gpt3Turbo_completion in gpt_utils.py: openai.api_base = "custom endpoint"

Here's the updated code:

```
def gpt3Turbo_completion():
    openai.api_key = ApiKeyManager.get_api_key("OPENAI")
    openai.api_base = "custom endpoint"
    max_retry = 5
    retry = 0
```
 
Please note that you need to replace "custom endpoint" with the actual custom endpoint URL you want to use.
